# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [1]:
import pandas as pd

In [67]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
market = pd.read_csv(url)
#display(market.head())

print("Columns:")
print(market.columns.tolist())

#display(market.isna().sum())

low_total_claim_amount = market[(market["Total Claim Amount"] < 1000) & (market["Response"] == "Yes")]
display(low_total_claim_amount.sort_values(by="Total Claim Amount", ascending=False))

display(market[['Income', 'Location Code', 'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim', 'Months Since Policy Inception']])

Columns:
['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value', 'Response', 'Coverage', 'Education', 'Effective To Date', 'EmploymentStatus', 'Gender', 'Income', 'Location Code', 'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim', 'Months Since Policy Inception', 'Number of Open Complaints', 'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type', 'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size', 'Vehicle Type']

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
3338,3338,AM26717,California,3123.080994,Yes,Basic,Bachelor,2/19/11,Unemployed,M,...,4.0,1,Personal Auto,Personal L1,Offer1,Agent,960.115399,SUV,Large,A
3558,3558,ST96866,Washington,3123.080994,Yes,Basic,Bachelor,2/19/11,Unemployed,M,...,4.0,1,Special Auto,Special L3,Offer1,Agent,960.115399,SUV,Large,A
4414,4414,JW24212,Oregon,3123.080994,Yes,Basic,Bachelor,2/19/11,Unemployed,M,...,4.0,1,Personal Auto,Personal L3,Offer1,Agent,960.115399,SUV,Large,A
7492,7492,YS74016,California,3123.080994,Yes,Basic,Bachelor,2/19/11,Unemployed,M,...,4.0,1,Personal Auto,Personal L2,Offer1,Agent,960.115399,SUV,Large,A
8377,8377,NT76210,Nevada,3123.080994,Yes,Basic,Bachelor,2/19/11,Unemployed,M,...,4.0,1,Personal Auto,Personal L3,Offer1,Agent,960.115399,SUV,Large,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2792,2792,CJ81799,Oregon,7462.926263,Yes,Extended,College,1/28/11,Employed,F,...,0.0,5,Personal Auto,Personal L2,Offer2,Call Center,7.345946,Two-Door Car,Small,NaN
7886,7886,EZ70589,Washington,7462.926263,Yes,Extended,College,1/28/11,Employed,F,...,0.0,5,Personal Auto,Personal L1,Offer2,Call Center,7.345946,Two-Door Car,Small,A
9131,9131,TR81766,California,7462.926263,Yes,Extended,College,1/28/11,Employed,F,...,0.0,5,Corporate Auto,Corporate L2,Offer2,Call Center,7.345946,Two-Door Car,Small,A
2400,2400,GJ99406,Arizona,7462.926263,Yes,Extended,College,1/28/11,Employed,F,...,0.0,5,Corporate Auto,Corporate L2,Offer2,Call Center,7.345946,Two-Door Car,Small,A
144,144,NR16284,California,7462.926263,Yes,Extended,College,1/28/11,Employed,F,...,0.0,5,Personal Auto,Personal L3,Offer2,Call Center,7.345946,Two-Door Car,Small,A

,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception
0,48029,Suburban,Married,61,7.0,52
1,0,Suburban,Single,64,3.0,26
2,22139,Suburban,Single,100,34.0,31
3,49078,Suburban,Single,97,10.0,3
4,23675,Suburban,Married,117,NaN,31
...,...,...,...,...,...,...
10905,0,Suburban,Married,253,NaN,40
10906,61146,Urban,Married,65,7.0,68
10907,39837,Rural,Married,201,11.0,63
10908,64195,Urban,Divorced,158,0.0,27
10909,0,Suburban,Single,101,31.0,1

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [68]:
yes_cust = market[market["Response"] == "Yes"]
avg_premium_types = (
    yes_cust
    .groupby(["Policy Type", "Gender"])[["Monthly Premium Auto", "Customer Lifetime Value", "Total Claim Amount"]]
    .mean()
)
display(avg_premium_types)

#Personal Auto customer have the highest claims amounts, but females pay the highest premiums with highest LTV. Males pay lower premiums with lower LTV.

                       Monthly Premium Auto  Customer Lifetime Value  \
Policy Type    Gender
Corporate Auto F                  94.301775              7712.628736
               M                  92.188312              7944.465414
Personal Auto  F                  98.998148              8339.791842
               M                  91.085821              7448.383281
Special Auto   F                  92.314286              7691.584111
               M                  86.343750              8247.088702

                       Total Claim Amount
Policy Type    Gender
Corporate Auto F               433.738499
               M               408.582459
Personal Auto  F               452.965929
               M               457.010178
Special Auto   F               453.280164
               M               429.527942

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [69]:
cust_by_state = (
    market
    .groupby("State")
    .size()
)


display(cust_by_state[cust_by_state > 500])

State
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
dtype: int64

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [70]:
cust_summary = (
    market
    .groupby(["Education", "Gender"])["Customer Lifetime Value"]
    .agg(["max", "min", "median"])
)
display(cust_summary.round(0).sort_values(by ="median"))

#High School has the highest median insurance and HS males have max insurance

                                 max     min  median
Education            Gender
Doctor               F       44856.0  2396.0  5332.0
Bachelor             M       67907.0  1898.0  5548.0
Doctor               M       32677.0  2268.0  5578.0
Master               M       50568.0  2272.0  5579.0
College              F       61850.0  1899.0  5624.0
Bachelor             F       73226.0  1904.0  5641.0
Master               F       51016.0  2418.0  5730.0
College              M       61135.0  1918.0  6006.0
High School or Below F       55277.0  2145.0  6040.0
                     M       83325.0  1941.0  6287.0

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [76]:
market["month"] = pd.to_datetime(market["Effective To Date"]).dt.month

C:\Users\chukk\AppData\Local\Temp\ipykernel_41708\406370126.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  market["month"] = pd.to_datetime(market["Effective To Date"]).dt.month

In [77]:
cust_by_state = (
    market
    .groupby(["State", "month"])
    .size()
)
display(cust_by_state)

State       month
Arizona     1        1008
            2         929
California  1        1918
            2        1634
Nevada      1         551
            2         442
Oregon      1        1565
            2        1344
Washington  1         463
            2         425
dtype: int64

In [90]:
long_table = market.pivot_table(
    index = "State",
    columns = "month",
    values = "Policy Type",
    aggfunc = "count"
)

display(long_table)

month          1     2
State
Arizona     1008   929
California  1918  1634
Nevada       551   442
Oregon      1565  1344
Washington   463   425

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [95]:
# your code goes here
cust_by_state = (
    market
    .groupby(["State", "month"])
    .size()
    .sort_values(ascending=False)
)
display(cust_by_state)

cust_by_state_total = (
    market
    .groupby(["State"])
    .size()
    .sort_values(ascending=False).head(3)
)
print("\n")
display(cust_by_state_total)

State       month
California  1        1918
            2        1634
Oregon      1        1565
            2        1344
Arizona     1        1008
            2         929
Nevada      1         551
Washington  1         463
Nevada      2         442
Washington  2         425
dtype: int64

State
California    3552
Oregon        2909
Arizona       1937
dtype: int64